name: Deploy Dev Infrastructure
on:
    push:
        branches:
            - main
        paths:
             - 'env/dev/**'
             - 'modules/**'
permissions:
    id-token: write
    contents: read
    pull-requests: write                

env:
    ARM_CLIENT_ID: "${{ secrets.ARM_CLIENT_ID}}"
    ARM_CLIENT_SECRET: "${{secrets.ARM_CLIENT_SECRET}}"
    ARM_SUBSCRIPTION_ID: "${{secrets.ARM_SUBSCRIPTION_ID}}"
    ARM_TENANT_ID: "${{secrets.ARM_TENANT_ID}}"
    TF_VAR_MONGO_URL: "${{secrets.TF_VAR_MONGO_URL}}"
    TF_VAR_PORT: "${{secrets.TF_VAR_PORT}}"
    TF_VAR_MONGO_DB: "${{secrets.TF_VAR_MONGO_DB}}"
    TF_VAR_MAIL_SECRET_KEY: "${{secrets.TF_VAR_MAIL_SECRET_KEY}}"
    TF_VAR_MAPBOX_ACCESS_TOKEN: "${{secrets.TF_VAR_MAPBOX_ACCESS_TOKEN}}"
    TF_VAR_MAIL_SERVICE: "${{secrets.TF_VAR_MAIL_SERVICE}}"
    TF_VAR_MAIL_USER: "${{secrets.TF_VAR_MAIL_USER}}"
    TF_VAR_MONGO_INITDB_ROOT_PASSWORD: "${{secrets.TF_VAR_MONGO_INITDB_ROOT_PASSWORD}}"
    TF_VAR_MONGO_INITDB_ROOT_USERNAME: "${{secrets.TF_VAR_MONGO_INITDB_ROOT_USERNAME}}"
    TF_VAR_DOMAIN: "${{secrets.TF_VAR_DOMAIN}}"


jobs:
    terraform-plan-apply:
        runs-on: ubuntu-latest
        env:
            ARM_SKIP_PROVIDER_REGISTRATION: true
            
        steps:
            - name: Clone git repository
              uses: actions/checkout@v4
            - name: Terraform setup
              uses: hashicorp/setup-terraform@v2
              with:
                terraform_version: 1.9.7
                terraform_wrapper: false  
            - name: Create SSH from secret
              run:  |
                mkdir -p ./env/dev/keys
                echo "${{ secrets.SSH_PRIVATE_KEY }}" > ./env/dev/keys/711incident_server
                echo "${{ secrets.SSH_PUBLIC_KEY }}" > ./env/dev/keys/711incident_server.pub
                chmod 777 ./env/dev/keys/711incident_server
                chmod 777 ./env/dev/keys/711incident_server.pub
                
            - name: Terraform init
              run: |
                export TF_LOG=DEBUG
                terraform -chdir=env/dev init -input=false
            - name: Terraform fmt
              run: terraform -chdir=env/dev fmt
            - name: Terraform plan
              run: terraform -chdir=env/dev plan
            - name: Terraform apply
              run: terraform -chdir=env/dev apply --auto-approve